name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: ghMetricsToken
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: GazPrash # Change this to your GitHub username
          filename: github.custom_metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          template: classic

          # Configure stats (as seen in the image)
          plugin_activity: yes           # Show recent activity (commits, issues, etc.)
          plugin_languages: yes          # Display most used languages
          plugin_repositories: yes       # Show repository stats (forks, stargazers, etc.)
          plugin_achievements: yes       # Enable achievement badges
          plugin_followup: yes           # Show following/follower stats
          plugin_traffic: yes            # Show repository traffic

          # Additional customization (colors and size)
          plugin_languages_details: percentage  # Display language percentage
          plugin_languages_ignored: 'html,css'  # Ignore certain languages (if needed)
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_threshold: 0%

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
